version: '2'

services:
  web: 
    image: aws-docker-test:latest
    ports:
      - "80:4444"
    networks:
      - backend_net
    volumes:
      - /data:/c/Users/lewis/DEV/aws-docker-test/data
networks:
  backend_net: