version: '3'

services:
  web: 
    image: aws-docker-test:latest
    ports:
      - "80:4444"
    networks:
      - backend_net
    volumes:
      - data:/home/ubuntu/aws-docker-test/data
volumes:
  data:
networks:
  backend_net: